### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JagaRamesh** [iamstannard/intro-data-capstone-musclehub#1]
Excellent job with the coding and the powerpoint presentation!

In coding, I am very pleased to see that you are arriving at the values for chi-square test using pandas instead of hard-coding numbers from pivot table
aApp =  app_pivot[app_pivot.ab_test_group == 'A'].Application.sum()
...
chi2_test = [[aApp, aNoApp],[bApp, bNoApp]]

Good job with the yticks and yTickLabels formulas!
yTicks = np.linspace(0,math.ceil(yMax*4)/4,numYTicks)
yTickLabels = [(str(math.trunc(x * 100)))+"%" for x in yTicks]

The powerpoint slides are sequenced well and communicated the information effectively. 
The font size is very small throughout the presentation. 
I would recommend to use a bigger font size. 
The matplotlib plots are created with proper title, xlabel and ylabel , but the fonts in the plots are too small to read.

The final summary is accurate for "Muscle hub A/B testing". 

One more point I would suggest is to make the fitness test optional and to analyze the retention rate of the customers who have taken the fitness test Vs who doesn't to gain insights on fitness tests' impact on long term customer retention.
 
Overall Great job!!! KEEP IT UP.

**Comment by iamstannard** [comment]
Thanks!
